language: cpp

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=Debug ATHENA_DOUBLE_PRECISION=OFF
  - CMAKE_BUILD_TYPE=Debug ATHENA_DOUBLE_PRECISION=ON
  - CMAKE_BUILD_TYPE=Release ATHENA_DOUBLE_PRECISION=OFF
  - CMAKE_BUILD_TYPE=Release ATHENA_DOUBLE_PRECISION=ON

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -D ATHENA_DOUBLE_PRECISION=${ATHENA_DOUBLE_PRECISION} .. && make

branches:
  except:
    - /\d\.\d\.\d/
